# Generated by Django 5.2.7 on 2025-10-19 11:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FilDeDiscussion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sujet', models.CharField(default='Contact (pas de sujet)', max_length=255)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('dernier_message', models.DateTimeField(auto_now=True)),
                ('lu_par_admin', models.BooleanField(default=False)),
                ('lu_par_visiteur', models.BooleanField(default=True)),
                ('visiteur', models.ForeignKey(limit_choices_to={'is_staff': False}, on_delete=django.db.models.deletion.CASCADE, related_name='fils_de_discussion', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-dernier_message'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField()),
                ('envoye_le', models.DateTimeField(auto_now_add=True)),
                ('expediteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_envoyes', to=settings.AUTH_USER_MODEL)),
                ('fil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='messagerie.fildediscussion')),
            ],
            options={
                'ordering': ['envoye_le'],
            },
        ),
    ]
