# Generated by Django 5.2.4 on 2025-10-20 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateurperso',
            name='photo_profil',
            field=models.ImageField(blank=True, null=True, upload_to='profils/', verbose_name='Photo de profil'),
        ),
    ]
