# Generated by Django 5.2.4 on 2025-10-21 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0002_utilisateurperso_photo_profil'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateurperso',
            name='biographie',
            field=models.TextField(blank=True, max_length=250, null=True, verbose_name='Biographie'),
        ),
        migrations.AddField(
            model_name='utilisateurperso',
            name='lien_facebook',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='Lien Facebook'),
        ),
        migrations.AddField(
            model_name='utilisateurperso',
            name='lien_instagram',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='Lien Instagram'),
        ),
        migrations.AddField(
            model_name='utilisateurperso',
            name='lien_whatsapp',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Numéro WhatsApp (ex: +243...)'),
        ),
    ]
