# Generated by Django 5.2.7 on 2025-10-19 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commentaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField()),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_publication', models.CharField(choices=[('TEXTE', 'Texte'), ('PHOTO', 'Photo'), ('VIDEO', 'Vidéo'), ('LIEN', 'Lien')], default='TEXTE', max_length=10)),
                ('titre', models.CharField(help_text='Titre de la publication', max_length=255)),
                ('contenu_texte', models.TextField(blank=True, help_text='Contenu principal (si type TEXTE)', null=True)),
                ('image', models.ImageField(blank=True, help_text='Image (si type PHOTO)', null=True, upload_to='publications/images/')),
                ('video_url', models.URLField(blank=True, help_text='Lien YouTube, Vimeo, etc. (si type VIDEO)', null=True)),
                ('lien_externe', models.URLField(blank=True, help_text='Lien du site (si type LIEN)', null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('epingle', models.BooleanField(default=False, help_text='Cocher pour garder en haut de la liste')),
                ('vues', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['-epingle', '-date_creation'],
            },
        ),
    ]
